name: Deploy React Vite to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: ⬇️ Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: npm run build
        env:
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_GA_ID: ${{ secrets.VITE_GA_ID }}

      - name: 🚀 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: aylabs

      - name: 💬 Discord Notification (Success)
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"🚀 Une nouvelle version du site vient d'être déployée !\"}" \
              ${{ secrets.DISCORD_WEBHOOK }}

      - name: 💬 Discord Notification (Failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"🚨 Il y a une erreur avec le workflow de déploiement ! @everyone\"}" \
              ${{ secrets.DISCORD_WEBHOOK }}
